### ISSUE TITLE
Support "open with"

### ISSUE THREAD

**Issue by treapster** [MateusRodCosta/Share2Storage#22] opened 2024-04-14 14:22 UTC
There are some apps which don't allow sharing and saving but have an option to open a file with another app. It would be really handy if this app could accept such intents and save the files.

**Comment by MateusRodCosta** [comment] 2024-04-14 17:21
@treapster That is already implemented, just enable "Intercept ACTION_VIEW intents" on the app settings.

**Comment by treapster** [comment] 2024-04-14 17:31
> @treapster That is already implemented, just enable "Intercept ACTION_VIEW intents" on the app settings.

Oh, thanks, for some reason f-droid installed an old version where the option wasn't present. After download it even suggested update but i declined - i thought it's a bug in f-droid that it suggests updates just after installation. But now i updated and it works!

**Comment by MateusRodCosta** [comment] 2024-04-14 18:09
Closing as duplicate of #19 (the issue that first requested this feature).

**Closed by MateusRodCosta** 2024-04-14 18:09 UTC
Labels: duplicate
