### ISSUE TITLE
[Feature] Change file name

### ISSUE THREAD

**Issue by srt54558** [MateusRodCosta/Share2Storage#9] opened 2024-01-01 12:27 UTC
When clicking on the file name, it should be possible to edit the file name

**Comment by MateusRodCosta** [comment] 2024-01-03 00:36
This already worked as it's provided by default by the file picker.

Just try to talk the file name on the file picker and it should allow you to rename the file.

Closing as a duplicate of #5.

**Closed** 2024-01-03 00:36 UTC
